### ISSUE TITLE
Is possible process optimize with Delayed Job?

### ISSUE THREAD

**Issue by monteirobrena** [jtescher/carrierwave-imageoptimizer#22]
I'm using `carrierwave-imageoptimizer` but in production environment was take so long time to process. I would like to know if there is any way to execute `process optimize: [{ quiet: true }]` with Delayed Job.

Thank you.

**Comment by jtescher** [comment]
Yep, you should be able to use gems like https://github.com/lardawge/carrierwave_backgrounder to process in the background.

**Comment by elsurudo** [comment]
Optimization will happen wherever the processing happens, so this isn't an issue with this particular gem, but rather you want to put the usual carrierwave processing in the background.

**Comment by jtescher** [comment]
Closing this for now, feel free to re open if you have other issues.

**Comment by ruby-kachan** [comment]
Hi guys! I used "carrierwave_backgrounder" but it's bad solving for me. Because when I used thumb version, after saving image I was need immediantely to view this version. But while carrierwave backgrounder  processing image, I can't did this.

And I solved my problem with sidekiq worker and carrierwave after save callback: 

It's my ImageUploader code: 
 

```ruby
   version :full do
      after :store, :optimize_image
   end
   
   def optimize_image file
      optimize_async(quiet: true, quality: 85, level: 7)
   end
```

It's my config/initializers/carrierwave.rb :
```ruby
module CarrierWave
  module MiniMagick
    def optimize_async(options)
      OptimizeImagesWorker.perform_async(current_path, options)
    end
  end
end
```

And my sidekiq worker:
